GET http://localhost:3000/assets

### Create a new asset
POST http://localhost:3000/assets
Content-Type: application/json

{
    "id": "asset1",    
    "symbol": "A1",
    "price": 100.00
}

### 
GET http://localhost:3000/wallets

### Create a wallet

POST http://localhost:3000/wallets
Content-Type: application/json

{
    "id": "wallet1",
    "assets": [
        {
            "id": "asset1",
            "symbol": "A1",
            "price": 100.00
        }
    ]
}

###

GET http://localhost:3000/wallets/wallet1/assets

### Add asset to wallet

POST http://localhost:3000/wallets/wallet1/assets
Content-Type: application/json

{
    "asset_id": "asset1",
    "shares": 10
}

###

POST http://localhost:3000/orders
Content-Type: application/json

{
    "asset_id": "asset1",
    "wallet_id": "wallet1",
    "shares": 10,
    "price": 50,
    "type": "BUY"
}
